name: clientes_quinta

on:
  schedule:
    - cron: "00 18 * * *"    # 15:00 ARG (Ajustado: GitHub usa UTC, Arg es UTC-3)
    - cron: "00 00 * * *"    # 21:00 ARG
  workflow_dispatch:         # Para ejecutarlo a mano cuando quieras

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar el bot
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        # Si el archivo está en una carpeta, recuerda poner: python carpeta/ejecutar_bot_clientes.py
        run: python ejecutar_bot_clientes.yml
